service: auth-api
provider:
  name: aws
  runtime: nodejs6.10
  environment:
    REGION: ${opt:region, self:provider.region}
    JWT_ISSUER: ${opt:jwt_issuer}
    JWT_SECRET: ${opt:jwt_secret}

  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:GetItem
        - dynamodb:PutItem
      Resource: arn:aws:dynamodb:*:*:table/Accounts
    - Effect: Allow
      Action:
        - dynamodb:GetItem
        - dynamodb:PutItem
      Resource: arn:aws:dynamodb:*:*:table/Clients
    - Effect: Allow
      Action:
        - dynamodb:Query
      Resource: arn:aws:dynamodb:*:*:table/Accounts/index/AccountNameIndex

functions:
  serveAuthorizationScreen:
    handler: dist/handler.serveAuthorizationScreen
    events:
      -
        http:
          path: oauth/authorize
          method: get
  processAuthorization:
    handler: dist/handler.processAuthorization
    events:
      -
        http:
          path: oauth/authorize
          method: post
  generateToken:
    handler: dist/handler.generateToken
    events:
      -
        http:
          path: oauth/token
          method: post
  tokenInfo:
    handler: dist/handler.tokenInfo
    events:
      -
        http:
          path: oauth/token_info
          method: post
  createAccount:
    handler: dist/handler.createAccount
    events:
      -
        http:
          path: accounts
          method: post
  serveNewAccountScreen:
    handler: dist/handler.serveNewAccountScreen
    events:
      -
        http:
          path: accounts/new
          method: get
resources:
  Resources:
    Accounts:
      Type: AWS::DynamoDB::Table
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: username
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        GlobalSecondaryIndexes:
          -
            IndexName: AccountNameIndex
            KeySchema:
              - AttributeName: username
                KeyType: HASH
            Projection:
              ProjectionType: ALL
            ProvisionedThroughput:
              ReadCapacityUnits: 1
              WriteCapacityUnits: 1
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: Accounts
    Clients:
      Type: AWS::DynamoDB::Table
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: Clients
package:
  exclude:
    - src/**
    - test/**
plugins:
  - serverless-dynamodb-local
  - serverless-offline
custom:
  dynamodb:
    start:
      port: 8000
      inMemory: true
      migrate: true
      seed: true