service: auth-api
provider:
  name: aws
  runtime: nodejs6.10
  environment:
    REGION: ${opt:region, self:provider.region}
    JWT_SECRET: ${opt:jwt_secret}
    CIPHER_KEY: ${opt:cipher_key}

  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:GetItem
        - dynamodb:PutItem
      Resource: arn:aws:dynamodb:*:*:table/Accounts

functions:
  serveAuthorizationScreen:
    handler: handler.serveAuthorizationScreen
    events:
      -
        http:
          path: oauth/authorize
          method: get
  processAuthorization:
    handler: handler.processAuthorization
    events:
      -
        http:
          path: oauth/authorize
          method: post
  token:
    handler: handler.token
    events:
      -
        http:
          path: oauth/token
          method: post
  createAccount:
    handler: handler.createAccount
    events:
      -
        http:
          path: accounts
          method: post
  serveNewAccountScreen:
    handler: handler.serveNewAccountScreen
    events:
      -
        http:
          path: accounts/new
          method: get
resources:
  Resources:
    Codes:
      Type: AWS::DynamoDB::Table
      DeletionPolicy: Retain
      Properties:
        TimeToLiveSpecification:
          AttributeName: ttl
          Enabled: true
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: Codes
    Accounts:
      Type: AWS::DynamoDB::Table
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: username
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        GlobalSecondaryIndexes:
          -
            IndexName: UsernameIndex
            KeySchema:
              - AttributeName: username
                KeyType: HASH
            Projection:
              ProjectionType: KEYS_ONLY
            ProvisionedThroughput:
              ReadCapacityUnits: 1
              WriteCapacityUnits: 1
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: Accounts
